var common_lib = require('./common_lib') ; // this needs to be the first line of the test file.
var fs = require('fs') ;
var monthly_taiex_crawler = require('../lib/crawlers/monthly_taiex_crawler') ;
var db = require('../dbconnection') ;
var TAIEX = db.TAIEX ;
var tech_functions = require('../lib/stats/technical_cal_functions') ;
var Promise = require('bluebird') ;

var golden_data = JSON.parse(fs.readFileSync('./test/taiex.json', 'utf8'));
var attrs_to_test = ['ma5', 'ma20', 'ma60', 'ma120', 'rsi5', 'rsi10', 'rsi6', 'rsi12', 'k9', 'd9', 'bias5', 'bias10', 'bias20', 'macd_12_26_9',
    'macd_diff9', 'dx14', 'p_di14', 'n_di14', 'psy12', 'psy24'] ;

describe('Use taiex to test technical functions', function(){
    this.timeout(100000) ;

    before(function(){
      return db.sequelize.sync() ;
    }) ;

    // the golden data is actually generated by using mysql workbench with data coming from 2015 and 2016
    // (I have manually compared the golden data with a few other websites.)
    // therefore, when doing the test, we also need to crawl the data for 2015 and 2016.
    it('Crawler data and compare with golden data', function(){
        var results = [] ;

        common_lib.get_yearly_data(monthly_taiex_crawler, 2015).then(function(result2015){
            results = results.concat(result2015) ;

            return common_lib.get_yearly_data(monthly_taiex_crawler, 2016) ;
        }).then(function(result2016){
            results = results.concat(result2016) ;

            return results ;
        }).then(function(records){
            tech_functions.updateMaAll(records, [5, 10, 20, 60, 120, 240]) ;
            tech_functions.updateBiasAll(records, [5, 10, 20]) ;
            tech_functions.updateRSIAll(records, [5, 10, 6, 12]) ;
            tech_functions.updateKDAll(records, [9]) ;
            tech_functions.updatePsyAll(records, [12, 24]) ;
            tech_functions.updateDMIAll(records, [14]) ;
            tech_functions.updateMACDAll(records, [12, 26, 9]) ;

            var promise_list = [] ;

            for(var i=0; i<records.length; i++){
                promise_list.push(TAIEX.upsert(records[i]).reflect()) ;
            }

            return Promise.all(promise_list) ;
        }).then(function(){
            return TAIEX.findAll() ;
        }).should.finally.has.resultIn(golden_data, attrs_to_test) ;
    }) ;
})
